#!/bin/sh
#
# redhawk-usrp-uhd-b205      init file for starting up the REDHAWK USRP UHD B205 Container
#
# chkconfig:   - 20 80
# description: Starts and stops the REDHAWK USRP UHD B205 Container
#

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/redhawk-usrp-uhd-b205"
prog="redhawk-usrp-uhd-b205"
CONTAINERNAME="rhb205"
OMNISERVICEIP="127.0.0.1"
RHDOMAINNAME="REDHAWK_DEV"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

logdir="/var/log/redhawk-usrp-uhd-b205"
logfile="${logdir}/log"
options=" -i $OMNISERVICEIP -d $RHDOMAINNAME -n -- --name=\"${CONTAINERNAME}\" > ${logfile}"
lockfile="/var/lock/subsys/redhawk-usrp-uhd-b205"

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon "$exec  $options  2>&1 &"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    docker kill -s SIGINT $CONTAINERNAME > /dev/null
    rm -f $lockfile
    success
    echo
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
